# Generated by Django 4.0.4 on 2022-05-16 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 5, 16, 13, 24, 3, 365892, tzinfo=utc)),
        ),
    ]
