# Generated by Django 4.0.4 on 2022-05-20 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='user_date',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='sessions',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
