# Generated by Django 4.0.4 on 2022-05-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_user_date_sessions_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_user',
            field=models.CharField(default='google@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password_user',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
